name: duality-rollkit
version: '3.8'
services:
  celestia-lc:
    image: ghcr.io/celestiaorg/celestia-node:bd96b3d
    volumes:
      - ${KEY_PATH}/celestia-lc/:${NODE_STORE}/keys:ro
      - ${PWD}/scripts/celestia-lc/:/scripts:ro
    ports:
      - 9092:9090
      - 26659:26659
    env_file:
      - ${PWD}/celestia-lc.env
    command: >
      /bin/sh -c '
        #!/bin/bash/
        /scripts/init.sh
        /scripts/start.sh'
    networks:
      localnet:
        ipv4_address: 192.168.10.2
  duality-rollkit-aggregator:
    image: duality-rollkit-aggregator:0.0.1
    volumes:
      - ${KEY_PATH}/duality-rollkit-aggregator/:/keys:ro
      - ${PWD}/scripts/duality/:/scripts:ro
    env_file:
      - ${PWD}/duality.env
    ports:
      - 26656:26656
      - 26657:26657
      - 9090:9090
      - 9091:9091
      - 1317:1317
    command: >
      /bin/sh -c '
        #!/bin/bash/
        /scripts/init.sh
        if [ ! -z ${GENESIS} ]
        then
          /scripts/genesis.sh
        fi
        /scripts/start.sh'
    networks:
      localnet:
        ipv4_address: 192.168.10.3

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/25