name: duality-rollkit
version: '3.8'
services:
  celestia-lc:
    image: ghcr.io/celestiaorg/celestia-node:bd96b3d
    ports:
      - 9092:9090
      - 26659:26659
    command: >
      /bin/sh -c '
        #!/bin/bash/

        # init the node
        /celestia light init \
          --p2p.network ${CELESTIA_LC_P2P_NETWORK}

        # add keys
        echo -n "${CELESTIA_LC_MNEMONIC}" | /cel-key add ${CELESTIA_LC_KEY_NAME} --recover --keyring-backend test \
          --node.type light --p2p.network ${CELESTIA_LC_P2P_NETWORK}

        # start node
        /celestia light start --p2p.network ${CELESTIA_LC_P2P_NETWORK} \
        	--core.ip ${CELESTIA_LC_NODE_ADDR} --gateway --gateway.addr ${CELESTIA_LC_GATEWAY_ADDR} --gateway.port ${CELESTIA_LC_GATEWAY_PORT}
      '
  duality-rollkit-aggregator:
    build:
      context: .
      dockerfile: Dockerfile
    image: duality-rollkit-aggregator:0.0.1
    env_file:
      - ${PWD}/duality.env
    ports:
      # rpc
      - 26656:26656
      # p2p
      - 26657:26657
      # grpc
      - 9090:9090
      # grpc-web
      - 9091:9091
      # api
      - 1317:1317
    command: >
      /bin/sh -c '
        #!/bin/bash/
        /scripts/init.sh
        if [ ! -z ${GENESIS} ]
        then
          /scripts/genesis.sh
        fi
        /scripts/start.sh'
