name: duality-rollkit
version: '3.8'
services:
  celestia-lc:
    image: ghcr.io/celestiaorg/celestia-node:bd96b3d
    ports:
      - 9092:9090
      - 26659:26659
    command: >
      /bin/sh -c '
        #!/bin/bash/

        # init the node
        /celestia light init \
          --p2p.network ${CELESTIA_LC_P2P_NETWORK}

        # add keys
        echo -n "${CELESTIA_LC_MNEMONIC}" | cel-key add custom-user --recover --keyring-backend test \
          --node.type light --p2p.network ${CELESTIA_LC_P2P_NETWORK}

        # start node
        /celestia light start --p2p.network ${CELESTIA_LC_P2P_NETWORK} \
        	--core.ip ${CELESTIA_LC_NODE_ADDR} --gateway --gateway.addr ${CELESTIA_LC_GATEWAY_ADDR} --gateway.port ${CELESTIA_LC_GATEWAY_PORT}
      '
    networks:
      localnet:
        ipv4_address: 192.168.10.2
  duality-rollkit-aggregator:
    image: duality-rollkit-aggregator:0.0.1
    env_file:
      - ${PWD}/duality.env
    ports:
      - 26656:26656
      - 26657:26657
      - 9090:9090
      - 9091:9091
      - 1317:1317
    command: >
      /bin/sh -c '
        #!/bin/bash/
        /scripts/init.sh
        if [ ! -z ${GENESIS} ]
        then
          /scripts/genesis.sh
        fi
        /scripts/start.sh'
    networks:
      localnet:
        ipv4_address: 192.168.10.3

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/25