version: 2.1
jobs:
  go-test:
    working_directory: ~/repo
    docker:
      - image: cimg/go:1.19.3
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go get ./...
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Run tests
          command: go test ./x/dex/keeper... -v
    docker-tests:
      working_directory: ~/repo
      machine: true
      steps:
        - checkout
        - run: LOG_LEVEL=warn docker-compose up --abort-on-container-exit -d
